### ISSUE TITLE
Make this footer a secondary nav with a ul instead of a punch of p tags.

### ISSUE THREAD

**Issue by tsdubose** [RUC-web/unit-3-project-clarajean#1]
https://github.com/RUC-web/unit-3-project-clarajean/blob/aa921872cf8601bab9c8b06c257a1e61e9106b13/home.html#L59

**Comment by clarajean** [comment]
footer.second_nav {
  display: flex;
  flex-direction: column;
  flex-wrap: wrap;
  margin-top: 10%;
  padding-right: 70%;
  background-color: rgb(244, 129, 85);
  list-style-type: none;
}
