### ISSUE TITLE
Banner image is not displaying correctly at mobile size

### ISSUE THREAD

**Issue by tsdubose** [RUC-web/unit-3-project-clarajean#3]

**Comment by clarajean** [comment]
.container {
    position: relative;
    text-align: center;
    color: black;
}

img {
  max-width: 100%;
  height: auto;
}

h1 {
  position: absolute;
    top: 35%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: .75em;
}
Should fix the main image.
